<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FloxStudios.Launcher.Publish</RootNamespace>
    <AssemblyName>launcher-publish</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Launcher.Core\Launcher.Core.csproj" />
  </ItemGroup>

</Project>
